name: Webpack Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0, 18.0]  # Specify Node.js versions to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: front/node_modules  # Adjust cache path to 'front/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: ./front  # Navigate to 'front' for installing dependencies

      - name: Build project
        run: npm run build
        working-directory: ./front  # Navigate to 'front' for building the project

      - name: Run tests
        run: npm test
        working-directory: ./front  # Navigate to 'front' for running tests (if applicable)

      - name: Upload Webpack build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: front/dist  # Adjust path to the 'dist' folder inside 'front'
